// <auto-generated />
namespace CTY_DVVT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTSX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTSX));
        
        string IMigrationMetadata.Id
        {
            get { return "202301311635182_addTSX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
